/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author mono-
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipla_
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuTransacciones = new javax.swing.JMenu();
        MenuIConsignar = new javax.swing.JMenuItem();
        MenuIRetirar = new javax.swing.JMenuItem();
        MenuConsultas = new javax.swing.JMenu();
        MenuIConsultarC = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(204, 255, 204));
        Escritorio.setForeground(new java.awt.Color(102, 255, 204));
        Escritorio.setPreferredSize(new java.awt.Dimension(388, 296));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuTransacciones.setText("Transacciones");

        MenuIConsignar.setText("Consignar");
        MenuIConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIConsignarActionPerformed(evt);
            }
        });
        MenuTransacciones.add(MenuIConsignar);

        MenuIRetirar.setText("Retirar");
        MenuIRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIRetirarActionPerformed(evt);
            }
        });
        MenuTransacciones.add(MenuIRetirar);

        jMenuBar1.add(MenuTransacciones);

        MenuConsultas.setText("Consultas");

        MenuIConsultarC.setText("Consultar Cliente");
        MenuIConsultarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIConsultarCActionPerformed(evt);
            }
        });
        MenuConsultas.add(MenuIConsultarC);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        MenuConsultas.add(MenuSalir);

        jMenuBar1.add(MenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuIConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIConsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIConsignarActionPerformed

    private void MenuIRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIRetirarActionPerformed

    private void MenuIConsultarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIConsultarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIConsultarCActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }

    public JMenu getMenuConsultas() {
        return MenuConsultas;
    }

    public void setMenuConsultas(JMenu MenuConsultas) {
        this.MenuConsultas = MenuConsultas;
    }

    public JMenuItem getMenuIConsignar() {
        return MenuIConsignar;
    }

    public void setMenuIConsignar(JMenuItem MenuIConsignar) {
        this.MenuIConsignar = MenuIConsignar;
    }

    public JMenuItem getMenuIConsultarC() {
        return MenuIConsultarC;
    }

    public void setMenuIConsultarC(JMenuItem MenuIConsultarC) {
        this.MenuIConsultarC = MenuIConsultarC;
    }

    public JMenuItem getMenuIRetirar() {
        return MenuIRetirar;
    }

    public void setMenuIRetirar(JMenuItem MenuIRetirar) {
        this.MenuIRetirar = MenuIRetirar;
    }

    public JMenuItem getMenuSalir() {
        return MenuSalir;
    }

    public void setMenuSalir(JMenuItem MenuSalir) {
        this.MenuSalir = MenuSalir;
    }

    public JMenu getMenuTransacciones() {
        return MenuTransacciones;
    }

    public void setMenuTransacciones(JMenu MenuTransacciones) {
        this.MenuTransacciones = MenuTransacciones;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenuItem MenuIConsignar;
    private javax.swing.JMenuItem MenuIConsultarC;
    private javax.swing.JMenuItem MenuIRetirar;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JMenu MenuTransacciones;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
